### ISSUE TITLE
Terminus 1.x uses ~/.terminus instead of ~/terminus

### ISSUE THREAD

**Issue by uberhacker** [lockr/lockr-terminus#2]
You might want to update your README.md instructions to include the "dot" in front of the `terminus` directory.  Also, if you can publish this plugin at packagist.org, it could then be installed via composer instead of git clone (although having both options is not a bad idea, either).

**Comment by tynor** [comment]
Thanks @uberhacker! The README has been updated and the package is now available on Packagist.
