### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by uberhacker** [lockr/lockr-terminus#3]
@tynor: You might want to tag a semver release (ie. `1.0.1`) so you can install via `composer create-project -d ~/.terminus/plugins/ lockr/lockr-terminus:~1`.  Right now, you need to install via `composer create-project --stability=dev -d ~/.terminus/plugins/ lockr/lockr-terminus` which installs from master.  If you tag a release, you can have a stable working version while you continue working on master for bug fixes and feature enhancements.

**Comment by tynor** [comment]
Looks like it was just a web hook setup I forgot to do to auto-update the Packagist information—just tried a 'composer require lockr/lockr-terminus:~1' and it worked.

**Comment by uberhacker** [comment]
Hey @tynor: I don't believe we should install Terminus plugins via `composer require`.  I know it's confusing because that is the installation method suggested on the packagist page.  The problem with `composer require` is it buries everything in the `vendor` directory.  Instead, we should install via `composer create-project -d ~/.terminus/plugins/ lockr/lockr-terminus:~1`.  You might want to put the Composer installation instructions in your README.md also.

**Comment by tynor** [comment]
For sure—I just used it to test the versioning.

I agree, I'll put Composer instructions above the raw Git clone since it definitely seems cleaner.
